### ISSUE TITLE
Allow retriggering a store submission

### ISSUE THREAD

**Issue by fregante** [fregante/browser-extension-template#96]
This workflow creates a version and then attempts to submit it all at once: https://github.com/fregante/ghatemplates/blob/main/webext/release.yml

It should probably take `workflow_dispatch` parameter to:

- use the latest release instead of creating a new one
- submit only to a specific store

**Comment by fregante** [comment]
Docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs

> * use the latest release instead of creating a new one

This might be easiest added as logic into https://github.com/fregante/daily-version-action so it can just fake `VERSION_CREATED` and the other ENVs

```yml
on:
  workflow_dispatch:
    inputs:
      use-existing:
        type: boolean
        description: Skip version generation and use the latest tag
```

```yml
      uses: fregante/daily-version-action@v2
      with:
        use-existing: github.event.inputs.use-existing
```

> * submit only to a specific store


Maybe possible via environments:

```yml
on:
  workflow_dispatch:
    inputs:
      environment:
        description: What store to deploy
        type: environment
```
